### ISSUE TITLE
SQL Server Linux Container running as StatefulSet shows status as Recovery Pending

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/ACS#54]
**Is this a request for help?**:

---
YES

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What happened**:
I created a custom SQL Server Linux container by following process as described below.

1. Create a standard SQL Sever Container by running `docker run -d -p 1433:1433 -e "SA_PASSWORD=<password>" -e "ACCEPT_EULA=Y" microsoft/mssql-server-linux
`
2. Create a custom database by running following script
```
GO
IF(db_id(N'snoopyshoppingcart') IS NULL)
BEGIN
	CREATE DATABASE snoopyshoppingcart 
		ON
			(
				NAME = ssc_dat,
				FILENAME = N'/ssc/ssc.mdf'
			)
		LOG ON  
			( 
				NAME = ssc_log,  
				FILENAME = N'/ssc/ssc.ldf'
			)
END;

GO
USE snoopyshoppingcart

GO
IF NOT EXISTS (SELECT * FROM sysobjects WHERE NAME='shopping' AND XTYPE='U')
BEGIN
	CREATE TABLE shopping
	(
		AddedOn datetime,
		ConnectionID nvarchar(100),
		IP nvarchar(20),
		CartItem nvarchar(100)
	)
END
```
Note that database files are created on path `/ssc`. This is a deviation from standard SQL Server files path `/var/opt/mssql/data`. I want to use `/ssc` - custom path to use as volumepoint and mount it on Azure Disk when creating a statefulset for this container.
3. Run `SHUTDOWN WITH NOWAIT`.
4. Stop SQL Server Container.
5. Commit changes by running` docker commit 8f maksh/snoopyshoppingcartdb` and creating a new image.
6. Push this custom image by running `docker push maksh/snoopyshoppingcartdb`

When I create a container from this custom image and run _locally_ (127.0.0.1, 1433), I can see that my custom database is available.

However, when I run this container as a statefulset on Kubernetes in Azure. Database shows status as **Recovery Pending**.
My k8s manifests below.

Secret (For sa password):
```
apiVersion: v1
kind: Secret
metadata:
  name: sqlsecret
type: Opaque
data:
  sapassword: UGFzc3dvcmQxMjM0
```
Storage Class:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurestorageclass
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: southeastasia
  storageAccount: <my-storage-account-in-same-rg-as-k8s>
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  name: sqlservice
  labels:
    app: sqlservice
spec:
  type: LoadBalancer
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlinux
```
StatefulSet:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sqlserverstatefulset
spec:
  serviceName: "sqlservice"
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlinux
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: sqlinux
          image: maksh/snoopyshoppingcartdb
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlsecret
                  key: sapassword
            - name: ACCEPT_EULA
              value: "Y"
          ports:
            - containerPort: 1433
          volumeMounts:
            - name: sql-persistent-storage
              mountPath: "/ssc"
  volumeClaimTemplates:
  - metadata:
      name: sql-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "azurestorageclass"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 16Gi
```
Pod logs following message:

```
2017-08-14 07:20:48.76 spid24s     Starting up database 'snoopyshoppingcart'.
 
2017-08-14 07:20:48.77 spid24s     Error: 17204, Severity: 16, State: 1.
 
2017-08-14 07:20:48.77 spid24s     FCB::Open failed: Could not open file /ssc/ssc.mdf for file number 1.  OS error: 2(The system cannot find the file specified.).
 
2017-08-14 07:20:48.78 spid9s      The resource database build version is 14.00.800. This is an informational message only. No user action is required.
 
2017-08-14 07:20:48.79 spid24s     Error: 5120, Severity: 16, State: 101.
 
2017-08-14 07:20:48.79 spid24s     Unable to open the physical file "/ssc/ssc.mdf". Operating system error 2: "2(The system cannot find the file specified.)".
 
2017-08-14 07:20:48.81 spid24s     Error: 17207, Severity: 16, State: 1.
 
2017-08-14 07:20:48.81 spid24s     FileMgr::StartLogFiles: Operating system error 2(The system cannot find the file specified.) occurred while creating or opening file '/ssc/ssc.ldf'. Diagnose and correct the operating system error, and retry the operation.
 
2017-08-14 07:20:48.81 spid9s      Starting up database 'model'.
 
2017-08-14 07:20:48.83 spid24s     File activation failure. The physical file name "/ssc/ssc.ldf" may be incorrect.
```
When I connect with SQL Server using external IP of service, I see my custom database is shown with status **Recovery Pending**

**What you expected to happen**:
I expect custom SQL Server database should be mounted on Azure Disk and in operational state.

**How to reproduce it** (as minimally and precisely as possible):
Follow steps as mentioned above.

**Anything else we need to know**:
A VHD disk gets created in storage account. This matches `persistentvolumeclaim `.
